export const drinksMap: { [key: string]: string } = {
  GIN_TONIC: "Gin Tonic",
  GIN_LEMON: "Gin Lemon",
  VODKA_LEMON: "Vodka Lemon",
  VODKA_REDBULL: "Vodka Redbull",
  MOJITO: "Mojito",
  LONG_ISLAND_ICE_TEA: "Long Island",
  MIAMI_ICE_TEA: "Miami Tea",
  NEGRONI: "Negroni",
  RUM_AND_COKE: "Cuba Libre",
  MARGARITA: "Margarita",
  PINA_COLADA: "Piña Colada",
  JAGER_BOMB: "Jäger Bomb",
  WHISKEY_SOUR: "Whiskey Sour",
  COSMOPOLITAN: "Cosmopolitan",
  SEX_ON_THE_BEACH: "Sex on the Beach",
  BLUE_HAWAIIAN: "Blue Hawaiian",
  DAIQUIRI: "Daiquiri",
  MAI_TAI: "Mai Tai",
  BLOODY_MARY: "Bloody Mary",
  MARTINI: "Martini",
  MANHATTAN: "Manhattan",
  OLD_FASHIONED: "Old Fashioned",
  SIDECAR: "Sidecar",
  SAZERAC: "Sazerac",
  KIR_ROYAL: "Kir Royale",
  CAIPIRINHA: "Caipirinha",
  CAIPIROSKA: "Caipiroska",
  SINGAPORE_SLING: "Singapore Sling",
  TEQUILA_SUNRISE: "Tequila Sunrise",
  WHITE_RUSSIAN: "White Russian",
  BLACK_RUSSIAN: "Black Russian",
  JACK_AND_COKE: "Jack e Cola",
  TEQUILA_SHOT: "Tequila Shot",
  BELLINI: "Bellini",
  MOJITO_ROSA: "Mojito Rosa",
  APEROL_SPRITZ: "Aperol Spritz",
  PINA_COLADA_SHOT: "Shot Piña Colada",
  LEMON_DROP_SHOT: "Shot Lemon Drop",
  RED_HEADED_SLUT: "Red Headed Slut",
  ZOMBIE: "Zombie",
  BLOODY_ZOMBIE: "Bloody Zombie",
  BLUE_MARTINI: "Blue Martini",
  TEQUILA_MOCKINGBIRD: "Tequila Mockingbird",
  LIQUID_MARIJUANA: "Liquid Marijuana",
  PURPLE_HOOTER: "Purple Hooter",
  ALABAMA_SLAMMER: "Alabama Slammer",
  FRENCH_CONNECTION: "French Connection",
  GOLDEN_MARGARITA: "Golden Margarita",
  LEMONADE_LONG_ISLAND: "Lemonade Long Island",
  GREEN_TEA_SHOT: "Green Tea Shot",
  ESPRESSO_MARTINI: "Espresso Martini",
  RASPBERRY_KAMIKAZE: "Raspberry Kamikaze",
  FROZEN_STRAWBERRY_DAIQUIRI: "Frozen Strawberry Daiquiri",
  VIRGIN_MARY: "Virgin Mary",
  VIRGIN_MOJITO: "Virgin Mojito",
  MOCKTAIL_ROYALE: "Mocktail Royale",
  SHIRLEY_TEMPLE: "Shirley Temple",
  VIRGIN_PINA_COLADA: "Virgin Piña Colada",
  VIRGIN_STRAWBERRY_DAIQUIRI: "Virgin Strawberry Daiquiri",
  WATER: "Acqua",
};

export const drinksList = Object.values(drinksMap);

export const gendersMap: { [key: string]: string } = {
  MALE: "Uomo",
  FEMALE: "Donna",
  NON_BINARY: "Non binario",
};
export const gendersList = Object.values(gendersMap);
